#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        example: !include ../examples/errorResponses/400.json
  
  401:
    body:
      application/json:
        example: !include ../examples/errorResponses/401.json
  
  403:
    body:
      application/json:
        example: !include ../examples/errorResponses/403.json

  404:
    body:
      application/json:
        example: !include ../examples/errorResponses/404.json

  408:
    body:
      application/json:
        example: !include ../examples/errorResponses/408.json
  
  429:
    body:
      application/json:
        example: !include ../examples/errorResponses/429.json

  500:
    body:
      application/json:
        example: !include ../examples/errorResponses/500.json

  503:
    body:
      application/json:
        example: !include ../examples/errorResponses/503.json