api:
 name: "product-pricing-eapi"
 id: "20486644"
 host: "product-pricing-papi-sok2p8.5sc6y6-4.usa-e2.cloudhub.io"
 basePath: "/api/product"
 createPath: "/create"
 deletePath: "/delete"
 updatePath: "/update"
 retrievePath: "/retrieve"
 clientId: "![obuZsa5h1u/MrJSBHXXiCyJfpLuc0n7ytb7BVkK6LiwEWM/PjPkmIw==]"
 clientSecret: "![+fMFTGU2mti8qbjFL5SMV43BCMVS9XCRJF4ggSK0WlkDE+67l7r37Q==]"
 retries: "1"
 frequency: "30000"
 timeout: "120000"