#%RAML 1.0 NamedExample
[
    {
        externalId: G132,
        name: Gold2 Whey,
        productCode: GW132,
        description: This is Gold2 Protein,
        currencyCode: USD,
        productPrice: 132
    },
    {
        externalId: MB130,
        name: MB,
        productCode: MP130,
        description: This is My Protein,
        currencyCode: USD,
        productPrice: 130
    }
]