#%RAML 1.0 NamedExample
{
  "results" : [
    {
        "description": "This is Muscle Blaze Protein",
        "productCode": "MB123",
        "externalId": "123",
        "type": "Product2",
        "name": "Muscle Blaze",
        "currencyCode": "EUR",
        "productPrice": "123.0",
        "convertedPrice": "142.63",
        "convertedCurrency": "USD"
    },
    {
        "description": "This is Muscle Blaze Protein",
        "productCode": "MB123",
        "externalId": "123",
        "type": "Product2",
        "name": "Muscle Blaze",
        "currencyCode": "EUR",
        "productPrice": "123.0",
        "convertedPrice": "142.63",
        "convertedCurrency": "USD"
    }
]
}