#%RAML 1.0 NamedExample
[
    {
	    	id : 01tdN000005EgpJQAS,
        externalId: GW132,
        name: Gold2 Whey,
        description: This is Gold2 Protein,
        currencyCode: USD,
        productPrice: 132
    },
    {
	    	id : 01tdN000005EgpJQAC,
        externalId: G130,
        name: Gold2,
        description: This is My Protein,
        currencyCode: USD,
        productPrice: 130
    }
]